
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_ANIMATIONS
#undef RGBLED_NUM
#define RGBLED_NUM 13
#undef RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 8

#undef RGBLIGHT_SAT_STEP
#define RGBLIGHT_SAT_STEP 8

#undef RGBLIGHT_VAL_STEP
#define RGBLIGHT_VAL_STEP 8

#undef PRODUCT
#define PRODUCT         DomsAMJ40
#define PERMISSIVE_HOLD
